be less noisy and send errors to stderr and not stdout

diff --git a/buildenv b/buildenv
--- a/buildenv
+++ b/buildenv
@@ -30,18 +30,18 @@ cat <<zz
   fi
 
   # Find the path to Python
-  echo "This only checks for the presence of python3. It does not install python3"
+  #echo "This only checks for the presence of python3. It does not install python3"
   PYTHON_PROG=\$(PATH="\$ZOPEN_OLD_PATH" /bin/type python3 | cut -f3 -d' ')
 
   # If Python is not found, exit with an error message
   if [ -z "\${PYTHON_PROG}" ]; then
-      echo "Python3 not found. Please install https://www.ibm.com/products/open-enterprise-python-zos"
+      echo "Python3 not found. Please install https://www.ibm.com/products/open-enterprise-python-zos" >&2
       return 1
   fi
 
   # Check the Python version, must be >= Python 3.8
   if ! \$PYTHON_PROG -c "import sys; sys.exit(not(sys.version_info[:2] >= (3, 8)))"; then
-      echo "Python version is not supported. Please install Python 3.8 or later - https://www.ibm.com/products/open-enterprise-python-zos"
+      echo "Python version is not supported. Please install Python 3.8 or later - https://www.ibm.com/products/open-enterprise-python-zos" >&2
       return 1
   fi
 
@@ -68,7 +68,7 @@ cat <<zz
     IFS=\$OLD_IFS
 
     if ! \${zz64found} ; then
-      echo "Unable to find libzz64.so for python"
+      echo "Unable to find libzz64.so for python" >&2
       return 1
     fi
   fi
